DROP DATABASE IF EXISTS employee_db; --DROP IF DATABASE ALREADY EXISTS
CREATE DATABASE employee_db; --CREATE IF IT DOESN'T
use employee_db; --DATABASE WE PLAN TO USE

--DEPARTMENT TABLE
CREATE TABLE department (
    id INT AUTO_INCREMENT, --AUTO INCREMENT WILL ++ THE ID'S FOR US
    name VARCHAR(30) NOT NULL --NAME IS MAX OF 30 CHARACTERS
    PRIMARY KEY (id) --PRIMARY KEY
);

CREATE TABLE role (
    id INT AUTO_INCREMENT, --AUTO INCREMENT WILL ++ THE ID'S FOR US
    title VARCHAR(30) NOT NULL, --TITLE IS MAX OF 30 CHARACTERS
    salary DEC NOT NULL,
    department_id INT,
    FOREIGN KEY (department_id) --FOREIGN KEY IS DEP_ID ATTACHING TO THE ID FROM DEPARTMENT.
    REFERENCES department(id)
    ON DELETE SET NULL
);

CREATE TABLE employee (
    id INT AUTO_INCREMENT, --AUTO INCREMENT WILL ++ THE ID'S FOR US
    first_name VARCHAR(30) NOT NULL, --HOLDS EMPLOYEES FIRST NAME/NAME IS MAX OF 30 CHARACTERS
    last_name VARCHAR(30) NOT NULL,
    role_id INT,
    manager_id INT NOT NULL,
    FOREIGN KEY (role_id) -- FOREIGN KEY ROLE_ID IS ATTACHED TO ROLE TABLE'S ID.
    REFERENCES role(id)
    FOREIGN KEY (manager_id) -- FOREIGN KEY MANAGER_ID IS ATTACHED TO EMPLOYEE ID.
    REFERENCES employee(id)
);


